# === Автоматически сгенерированный список для DIRECT (Optimized) ===
# Обновлено: 2026-07-18 09:47:37

# --- Домены ---
avito.st
avtodor-tr.ru
b2c-ticket-sentry.onelya.ru
bitrix.info
bkvet.ru
championat.com
consultant.ru
counter.yadro.ru
dzvr.ru
emex.ru
fairplay-proxy.ott.yandex.ru
gorzdrav.spb.ru
gosuslugi.ru
gov.ru
graphql.kinopoisk.ru
gu-st.ru
ixbt.com
ixbt.games
ixbt.photo
ixbt.pro
kpcdn.net
kp.house
lemanapro.ru
lenta.com
leroymerlin.ru
livejournal.com
magnit.ru
mobileapp.russianpost.ru
mosenergosbyt.ru
mosreg.ru
mos.ru
mycdn.me
nalog.ru
ngenix.net
ozon.ru
ozonusercontent.com
pesc.ru
pochta.ru
r-99.com
reso.ru
ru.com
ru.net
russianfood.com
rzd.ru
sberbank.com
showip.net
tsargrad.tv
userapi.com
vk.cc
vk.com
vk.me
vkuseraudio.net
vshark.ttk.ru
widevine-proxy.ott.yandex.ru
yadi.sk
yandex-bank.net
yandex.cloud
yandex.com
yandex.net
yandex.st
yaplakal.com
yastatic.net

# --- IPv4 ---

# --- IPv6 ---
